/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.marton;

import client.Client;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONObject;

/**
 *
 * @author vassv
 */
public class Karbantarto extends javax.swing.JFrame {

    private Client client;
    private List karbanTartasok = new ArrayList();
    
    public Karbantarto(Client c) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.client = c;
        tablazatGeneralo(karbanTartasok);
        elfogad.setEnabled(false);
        elutasit.setEnabled(false);
        kesz.setEnabled(false);
        nincsKesz.setEnabled(false);
        
        
    }

    public void tablazatGeneralo(List karbanTartasok){
        this.napiFeladatok.removeAll();
        String[] titles = {"eszközID", "típus", "súlyosság", "elfogadás állapota", "feladat állapota"};
        //String[][] datas = new String[karbanTartasok.size()][4];  EZT KELL KIVENNI
        String[][] datas = new String[1][5];
        for(int i = 0; i < karbanTartasok.size(); i++){
            /*datas[i][0] = karbanTartasok.get(i).getEszkozID();    EZEKET IS  
            datas[i][1] = karbanTartasok.get(i).getTipus();
            datas[i][2] = karbanTartasok.get(i).getSulyossag;
            datas[i][3] = karbanTartasok.get(i).getElfogadasAllapota();
            datas[i][4] = karbanTartasok.get(i).getFeladatAllapota();*/
        }
        datas[0][0] = "asd";
        datas[0][1] = "dsa";
        datas[0][2] = "cad";
        datas[0][3] = "dec";
        datas[0][4] = "Nincs kész";
        this.napiFeladatok.setModel(new DefaultTableModel(datas, titles));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nev = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kijelentkezes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        napiFeladatok = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        elfogad = new javax.swing.JButton();
        elutasit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        helyszin = new javax.swing.JLabel();
        kesz = new javax.swing.JButton();
        nincsKesz = new javax.swing.JButton();
        lepesek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nev.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nev.setText("Név");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Bejelentkezett karbantartó:");

        kijelentkezes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kijelentkezes.setText("Kijelentkezés");
        kijelentkezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kijelentkezesActionPerformed(evt);
            }
        });

        napiFeladatok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        napiFeladatok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                napiFeladatokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(napiFeladatok);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Napi feladatok");

        elfogad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        elfogad.setText("Elfogad");
        elfogad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elfogadActionPerformed(evt);
            }
        });

        elutasit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        elutasit.setText("Elutasit");
        elutasit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elutasitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("A következő feladat helyszíne:");

        helyszin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helyszin.setText("Helyszín");

        kesz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kesz.setText("Készen van");
        kesz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keszActionPerformed(evt);
            }
        });

        nincsKesz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nincsKesz.setText("Nincs készen");
        nincsKesz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nincsKeszActionPerformed(evt);
            }
        });

        lepesek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lepesek.setText("A feladatok elvégzésének lépései");
        lepesek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lepesekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(nev, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kijelentkezes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(helyszin, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(elfogad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(elutasit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(kesz, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(nincsKesz, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(lepesek, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(740, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kijelentkezes, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(nev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(elutasit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elfogad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kesz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nincsKesz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(202, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(helyszin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lepesek, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(520, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kijelentkezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kijelentkezesActionPerformed
        String JSONtext, JSONreply = "";
        JSONObject obj = new JSONObject();
//        obj.put("hash", hash);
        obj.put("code", 2);
        JSONtext = obj.toJSONString();
        System.out.println(JSONtext);
        
        dispose();
    }//GEN-LAST:event_kijelentkezesActionPerformed

    private void elfogadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elfogadActionPerformed
        napiFeladatok.setValueAt("Elfogadva", napiFeladatok.getSelectedRow(), 3);
        //következő feladat helyszín változtatása
    }//GEN-LAST:event_elfogadActionPerformed

    private void napiFeladatokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_napiFeladatokMouseClicked
        if(napiFeladatok.getSelectedRow() != -1){
            elfogad.setEnabled(true);
            elutasit.setEnabled(true);
            kesz.setEnabled(true);
            nincsKesz.setEnabled(true);
        }
    }//GEN-LAST:event_napiFeladatokMouseClicked

    private void elutasitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elutasitActionPerformed
        napiFeladatok.setValueAt("Semleges", napiFeladatok.getSelectedRow(), 3);
        //következő feladat helyszín változtatása
    }//GEN-LAST:event_elutasitActionPerformed

    private void keszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keszActionPerformed
        napiFeladatok.setValueAt("Kész", napiFeladatok.getSelectedRow(), 4);
    }//GEN-LAST:event_keszActionPerformed

    private void nincsKeszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nincsKeszActionPerformed
        napiFeladatok.setValueAt("Nincs kész", napiFeladatok.getSelectedRow(), 4);
    }//GEN-LAST:event_nincsKeszActionPerformed

    private void lepesekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lepesekActionPerformed
        JOptionPane.showMessageDialog(rootPane, "ide jönnek az utasítások\nna meg ide", "Lépések", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lepesekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karbantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karbantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karbantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karbantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karbantarto(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton elfogad;
    private javax.swing.JButton elutasit;
    private javax.swing.JLabel helyszin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kesz;
    private javax.swing.JButton kijelentkezes;
    private javax.swing.JButton lepesek;
    private javax.swing.JTable napiFeladatok;
    private javax.swing.JLabel nev;
    private javax.swing.JButton nincsKesz;
    // End of variables declaration//GEN-END:variables
}
