/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.akos;

import client.Client;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author Ákos
 */
public class ResponsibleForAssets extends javax.swing.JFrame {

    /**
     * Creates new form ResponsibleForAssets
     */

    private Client client;
    private String [] kategoriak;
    private JSONArray tools;
    private JSONArray array;
    private DefaultTableModel dtm;
    
    public ResponsibleForAssets(Client c) {
        initComponents();        
        client = c;
        NAME_LABEL.setText(client.getName());
        
        array = client.getCategorys();
        kategoriak = new String[array.size()];
        for (int i = 0; i < array.size(); i++) {
            JSONObject obj = (JSONObject)array.get(i);
            kategoriak[i] = obj.get("name").toString();
        }
        //CATEGORY_COMBOBOX.setModel(new DefaultComboBoxModel(kategoriak.clone()));
        //SUBCATEGORY_COMBOBOX.setModel(new DefaultComboBoxModel(kategoriak.clone()));
        //SUBCATEGORY_COMBOBOX.setEnabled(false);
        
        tools = client.getTools();
//        int size1 = tools.size();
//        int size2 = ((JSONObject)tools.get(0)).size();
//        Object [][] data = new Object[size1][size2];
//        for (int i = 0; i < tools.size(); i++) {
//            JSONObject obj = ((JSONObject)tools.get(i));
//            data[i][0] = obj.get("azonosito");
//            data[i][0] = obj.get("name");
//            data[i][0] = obj.get("elhelyezkedes");
//        }
//        TOOLS_TABLE.setModel(new DefaultTableModel(data, new String []{"Azonosító", "Megnevezés", "Elhelyezkedés"}));
        dtm=(DefaultTableModel) TOOLS_TABLE.getModel();
        for (int i = 0; i < tools.size(); i++) {
            JSONObject obj = (JSONObject)tools.get(i);
            System.out.println(obj.get("id").toString());
            int sorsz = Integer.parseInt(obj.get("id").toString());
            String nev = obj.get("name").toString();
            String hely = obj.get("elhelyezkedes").toString();
            
            dtm.addRow(new Object[]{sorsz,nev,hely,});
        }
        
        CATEGORY_COMBOBOX2.setModel(new DefaultComboBoxModel<>(kategoriak.clone()));
        
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                client.close();
                super.windowClosing(e); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITLE_LABEL = new javax.swing.JLabel();
        NAME_LABEL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TOOLS_TABLE = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        azonositoField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nevField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        elhelyezkedesField = new javax.swing.JTextField();
        EszkozFelvitelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        leirasField = new javax.swing.JTextArea();
        CATEGORY_COMBOBOX2 = new javax.swing.JComboBox<>();
        LOGOUT_BUTTON = new javax.swing.JButton();
        NEW_CATEGORY_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eszközfelelős");

        TITLE_LABEL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TITLE_LABEL.setText("Eszközfelelős kezelőfelület - Bejelentkezve:");

        NAME_LABEL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NAME_LABEL.setText("Bedő Sanyi");

        TOOLS_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Azonosító", "Név", "Elhelyezkedés"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TOOLS_TABLE.setColumnSelectionAllowed(false);
        TOOLS_TABLE.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TOOLS_TABLE);
        TOOLS_TABLE.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (TOOLS_TABLE.getColumnModel().getColumnCount() > 0) {
            TOOLS_TABLE.getColumnModel().getColumn(0).setResizable(false);
            TOOLS_TABLE.getColumnModel().getColumn(1).setResizable(false);
            TOOLS_TABLE.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Lekérdezés");

        jLabel5.setText("Azonosító:");

        azonositoField.setEnabled(false);

        jLabel6.setText("Név:");

        nevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Kategória:");

        jLabel8.setText("Leírás:");

        jLabel9.setText("Elhelyezkedés:");

        EszkozFelvitelButton.setText("Felvitel");
        EszkozFelvitelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EszkozFelvitelButtonActionPerformed(evt);
            }
        });

        leirasField.setColumns(20);
        leirasField.setRows(5);
        jScrollPane2.setViewportView(leirasField);

        LOGOUT_BUTTON.setText("Kijelentkezés");
        LOGOUT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT_BUTTONActionPerformed(evt);
            }
        });

        NEW_CATEGORY_BUTTON.setText("Új kategória felvétele");
        NEW_CATEGORY_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_CATEGORY_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(azonositoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nevField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CATEGORY_COMBOBOX2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(elhelyezkedesField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 64, Short.MAX_VALUE)
                                .addComponent(EszkozFelvitelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TITLE_LABEL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NAME_LABEL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LOGOUT_BUTTON)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(NEW_CATEGORY_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITLE_LABEL)
                    .addComponent(NAME_LABEL)
                    .addComponent(LOGOUT_BUTTON))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(azonositoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(nevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(elhelyezkedesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CATEGORY_COMBOBOX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8))
                    .addComponent(EszkozFelvitelButton))
                .addGap(32, 32, 32)
                .addComponent(NEW_CATEGORY_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nevFieldActionPerformed

    private void EszkozFelvitelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EszkozFelvitelButtonActionPerformed
        JSONObject tmp;
        String azonosito = azonositoField.getText().trim(),
        name = nevField.getText().trim(),
        kategoria = CATEGORY_COMBOBOX2.getSelectedItem().toString().trim();
        tmp = (JSONObject)array.get(CATEGORY_COMBOBOX2.getSelectedIndex());
        int id = Integer.parseInt(tmp.get("id").toString());
        String elhelyezkedes = elhelyezkedesField.getText().trim(),
        leiras = leirasField.getText().trim();
        if(name.isEmpty() || kategoria.isEmpty() || elhelyezkedes.isEmpty() || leiras.isEmpty()){
            JOptionPane.showMessageDialog(this, "Minden mező kitöltése kötelező", "Hiba", JOptionPane.WARNING_MESSAGE);
        }else if (client.addItem(azonosito, name, id, elhelyezkedes, leiras)){
            //majd táblázat frissítése
            azonositoField.setText("");
            nevField.setText("");
            CATEGORY_COMBOBOX2.setSelectedIndex(0);
            elhelyezkedesField.setText("");
            leirasField.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Az adatrögzítés nem sikerült, próbáld újra.", "Hiba", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EszkozFelvitelButtonActionPerformed

    private void LOGOUT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUT_BUTTONActionPerformed
        client.LogOut();
        new SignIn(client).setVisible(true);       
        dispose();
    }//GEN-LAST:event_LOGOUT_BUTTONActionPerformed

    private void NEW_CATEGORY_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_CATEGORY_BUTTONActionPerformed
        new newCategory(this, true, client, kategoriak).setVisible(true);
    }//GEN-LAST:event_NEW_CATEGORY_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResponsibleForAssets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResponsibleForAssets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResponsibleForAssets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResponsibleForAssets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResponsibleForAssets().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CATEGORY_COMBOBOX2;
    private javax.swing.JButton EszkozFelvitelButton;
    private javax.swing.JButton LOGOUT_BUTTON;
    private javax.swing.JLabel NAME_LABEL;
    private javax.swing.JButton NEW_CATEGORY_BUTTON;
    private javax.swing.JLabel TITLE_LABEL;
    private javax.swing.JTable TOOLS_TABLE;
    private javax.swing.JTextField azonositoField;
    private javax.swing.JTextField elhelyezkedesField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea leirasField;
    private javax.swing.JTextField nevField;
    // End of variables declaration//GEN-END:variables
}
